language: cpp

sudo: false

addons:
  postgresql: "9.3"

matrix:
  include:
    - os: osx
      compiler: clang
      env: JOBS=12
    - os: linux
      compiler: clang
      env: JOBS=12
    - os: linux
      compiler: gcc
      env: JOBS=6

install:
 - if [[ $(uname -s) == 'Linux' ]]; then psql -U postgres -c 'create database template_postgis;' -U postgres; psql -U postgres -c 'create extension postgis;' -d template_postgis -U postgres; fi;
 - if [[ $(uname -s) == 'Darwin' ]]; then brew install bash; export PATH="$(brew --prefix)/bin":${PATH}; fi;
 - echo `which bash`

script:
 - source bootstrap.sh
 - ./configure
 - cat config.log
 - make
 - make test-local
