language: cpp

addons:
  postgresql: "9.3"

compiler:
 - clang
 - gcc

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:mapnik/boost-backports-1-54
 - sudo apt-get update -qq
 - sudo apt-get install -qq make libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev libcairo-dev python-cairo-dev libsqlite3-dev postgresql-server-dev*

script:
 - ./configure CXX=${CXX} CC=${CC} DEBUG=False DEMO=False BINDINGS='python' CPP_TESTS=True CAIRO=True FAST=True && JOBS=2 make
 - make test-local

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
