language: cpp

compiler:
 - gcc

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:mapnik/boost
 - echo 'yes' | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq gcc-4.7 g++-4.7 libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev

script:
 - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.7" && export CC="gcc-4.7"; fi; ./configure CXX=${CXX} CC=${CC} DEMO=False BINDINGS=python CPP_TESTS=True CAIRO=False FAST=True || cat config.log
 - make
 - make test-local

branches:
  only:
    - master
    - 2.3.x

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
