language: cpp

sudo: false

git:
  depth: 2

addons:
  postgresql: "9.4"
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.6
    packages:
     - clang-3.6

cache:
  directories:
  - mason_packages
  - $HOME/.ccache

matrix:
  include:
    - os: linux
      compiler: clang
      env: JOBS=8
    - os: linux
      compiler: gcc
      env: JOBS=6
    - os: osx
      compiler: clang
      env: JOBS=8 COVERAGE=true

before_install:
 - export COVERAGE=${COVERAGE:-false}

install:
 - if [[ $(uname -s) == 'Linux' ]]; then
    psql -U postgres -c 'create database template_postgis;' -U postgres;
    psql -U postgres -c 'create extension postgis;' -d template_postgis -U postgres;
    export CXX="ccache clang++-3.6";
    export CC="ccache clang-3.6";
    export PYTHONPATH=$(pwd)/mason_packages/.link/lib/python2.7/site-packages;
   fi;

script:
 - source bootstrap.sh
 - if [[ ${COVERAGE} == true ]]; then ./configure CUSTOM_LDFLAGS='--coverage' CUSTOM_CXXFLAGS='--coverage' CUSTOM_CFLAGS='--coverage' DEBUG=True; else ./configure; fi;
 - make
 - git clone --depth=1 https://github.com/mapnik/test-data test-data
 - git clone --depth=1 https://github.com/mapbox/mapnik-test-data tests/data/mapnik-test-data
 - make test
 - PYTHONUSERBASE=$(pwd)/mason_packages/.link pip install --user cpp-coveralls
 - if [[ ${COVERAGE} == true ]]; then ./mason_packages/.link/bin/cpp-coveralls --build-root . --gcov-options '\-lp' --exclude mason_packages --exclude .sconf_temp --exclude benchmark --exclude deps --exclude scons --exclude test --exclude demo --exclude docs --exclude fonts --exclude utils > /dev/null; fi;
 - if [[ ${COVERAGE} != true ]]; then make bench; fi;
