language: cpp

sudo: false

addons:
  postgresql: "9.3"
  # http://docs.travis-ci.com/user/apt/
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

matrix:
  include:
    - os: osx
      compiler: clang
      env: JOBS=8 COVERAGE=true
    - os: osx
      compiler: clang
      env: JOBS=8
    - os: linux
      compiler: clang
      env: JOBS=8
    - os: linux
      compiler: gcc
      env: JOBS=6

before_install:
 - export COVERAGE=${COVERAGE:-false}

install:
 - if [[ $(uname -s) == 'Linux' ]]; then
    psql -U postgres -c 'create database template_postgis;' -U postgres;
    psql -U postgres -c 'create extension postgis;' -d template_postgis -U postgres;
    export CXX="clang++-3.5";
    export CC="clang-3.5";
   fi;

script:
 - source bootstrap.sh
 - if [[ ${COVERAGE} == true ]]; then ./configure CUSTOM_LDFLAGS='--coverage' CUSTOM_CXXFLAGS='--coverage' CUSTOM_CFLAGS='--coverage' DEBUG=True; else ./configure; fi;
 - make
 - git clone --depth=1 https://github.com/mapnik/test-data test-data
 - git clone --depth=1 https://github.com/mapbox/mapnik-test-data tests/data/mapnik-test-data
 - make test
 - if [[ ${COVERAGE} == true ]]; then
      brew install pyenv;
      eval "$(pyenv init -)";
      pyenv install 2.7.6;
      pyenv global 2.7.6;
      pyenv rehash;
      pip install cpp-coveralls;
      pyenv rehash;
     fi;
 - if [[ ${COVERAGE} == true ]]; then cpp-coveralls --build-root . --gcov-options '\-lp' --exclude mason_packages --exclude .sconf_temp --exclude benchmark --exclude deps --exclude scons --exclude tests --exclude py2cairo-1.10.0 --exclude demo --exclude docs --exclude fonts --exclude utils > /dev/null; fi;
 - if [[ ${COVERAGE} != true ]]; then make bench; fi;
