environment:
  msvs_toolset: 14
  FASTBUILD: 1
  matrix:
    - platform: x64
      configuration: Release

os: Visual Studio 2015

#shallow_clone: true
# limit clone to latest 5 commits
clone_depth: 5

build_script:
  - scripts\build-appveyor.bat

after_build:
  - 7z a visual-test-results.zip C:\tmp\mapnik-visual-images\visual-test-results

artifacts:
  - path: mapnik-gyp\msbuild-summary.txt
    name: msbuild-summary.txt
  - path: mapnik-gyp\msbuild-errors.txt
    name: msbuild-errors.txt
  - path: mapnik-gyp\msbuild-warnings.txt
    name: msbuild-warnings.txt
  - path: visual-test-results.zip
    name: visual-test-results.zip

test: off
deploy: off
