environment:
  msvs_toolset: 14
  BOOST_VERSION: 58
  matrix:
    - platform: x64
      configuration: Release

os: Visual Studio 2015

shallow_clone: true

install:
  - scripts\build-appveyor.bat

build: off
test: off
deploy: off
